server:
  port: 8888

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: springcloud-consumer-route
          uri: lb://springcloud-consumer
          predicates:
          - Path=/consumer/**
          - MyTimeLimit=06:00:00,23:00:00,true
          filters:
          - StripPrefix=1
          #限流
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 2
              redis-rate-limiter.burstCapacity: 5
              key-resolver: "#{@ipKeyResolver}"
          #Hystrix降级回退
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback
      globalcors:
        cors-configurations:
          '[/**]':
            #允许访问ip
#            allowed-origins: "*"
            allowed-origins:
            - "http://localhost:8888"
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods:
            - OPTIONS
            - GET
            - POST

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    org.springframework.cloud.gateway: trace
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@server2:9092/eureka/,http://root:root@server1:9091/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}



